  const TripActionTypes = {
    TRIP_SET_CURRENT: 'TRIP_SET_CURRENT',
    TRIP_LOAD_LIST: 'TRIP_LOAD_LIST',
    TRIP_LOAD_DATA: 'TRIP_LOAD_DATA',
    TRIP_LOAD_USERLIST: 'TRIP_LOAD_USERLIST',
    TRIP_LOAD_JOURNALS: 'TRIP_LOAD_JOURNALS'
  };

  export default TripActionTypes;
