const UserActionTypes = {
  USER_SET_DATA: 'USER_SET_DATA',
  USER_SET_LOGGED_IN: 'USER_SET_LOGGED_IN',
  USER_SET_LOGIN_LOGIN_STATE: 'USER_SET_LOGIN_LOGIN_STATE',
  USER_SET_LOGIN_FORM_ERROR: 'USER_SET_LOGIN_FORM_ERROR',
  USER_SET_LIST: 'USER_SET_LIST',
  USER_SET_TEMP_CODE: 'USER_SET_TEMP_CODE',
  USER_INIT_EDIT: 'USER_INIT_EDIT',
  USER_SET_EDIT: 'USER_SET_EDIT',
  USER_CLEAR_EDIT: 'USER_CLEAR_EDIT'
};

export default UserActionTypes;
